// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftjjkqanssuwumpzqjiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0amprcWFuc3N1d3VtcHpxaml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxODk0MTQsImV4cCI6MjA4NDc2NTQxNH0.kCdY7iwQuA_tNIroxm3VVUqmEDdlTTLMAsiyUld1W2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});